Took 484 binary data in resources
Oyun-Teknolojileri/ToolKit pull request #1
Opened 2022-11-08 19:04 UTC by fcturan20

[TOOK-484](https://oyunteknolojileri.atlassian.net/browse/TOOK-484?atlOrigin=eyJpIjoiZDQyYTVmZmI3Y2ZmNGE1ODhhZjYwYzdlOGYyOWE2OTAiLCJwIjoiaiJ9)

2022-11-09 09:51 UTC, afraidofdark requested changes

2022-11-09 09:51 UTC, afraidofdark commented on Editor/UI.cpp
> +      if (ImGui::MenuItem("Save All Resources"))
good ! move the function to App

2022-11-09 14:11 UTC, fcturan20 commented on ToolKit/Mesh.cpp
> +    // m_material->Save(onlyIfDirty);
It was causing crash. I couldn't figure out why.

2022-11-09 14:26 UTC, fcturan20 commented on ToolKit/Mesh.cpp
> +    MeshRawCPtrArray cMeshes;
Because we don't have multi mesh component.
Current import system searches the import scene. If an entity is only used to store a submesh (body scene has seperate entities for head, hand etc.), import merges it to main entity by storing the submesh in submesh list of main mesh.

2022-11-10 12:13 UTC, afraidofdark approved these changes

2022-11-10 17:15 UTC, merged