problem fixed, idk is there any better way of doing this,
Oyun-Teknolojileri/ToolKit pull request #126
Opened 2023-03-14 17:29 UTC by benanil

when prefab saved as invisible but child's are visible in that case child's shouldn't show up but they are showing up. 
I fix this issue by deep set visible.

2023-03-14 17:43 UTC, benanil commented
took-751

2023-03-15 07:22 UTC, afraidofdark requested changes

2023-03-15 07:22 UTC, afraidofdark commented on ToolKit/Scene.cpp
> +      prefab->SetVisibility(prefab->GetVisibleVal(), true);
this will override prefab's children's original settings.
what we wan't here is, if an entity is child of a prefab, it's GetVisibleVal should disregard its own value and use master prefab's value.

For entity class, you can write a function IsVisible and this uses GetVisibilityVal internally, but incase, the entity is a part of prefab, it can return paren't objects visibility. This prevent overriding prefab's child visibility value.

2023-03-15 15:46 UTC, afraidofdark commented on ToolKit/Util.h
> +  void EraseIf(T& vec, Pred pred)
try adapting std styling if you are extending std functions.

2023-03-15 16:13 UTC, benanil commented on ToolKit/Util.h
> +  void EraseIf(T& vec, Pred pred)
I've tried to do that but there is a conflict because std has a function with same name and different arguments.

2023-03-15 16:16 UTC, benanil commented on ToolKit/Util.h
> +  void EraseIf(T& vec, Pred pred)
nope std doesn't have erase_if I've tried remove_if but yeah I will rename and resolve this conversation

2023-03-16 13:21 UTC, merged