Run in window save last res took 805
Oyun-Teknolojileri/ToolKit pull request #156
Opened 2023-04-18 00:31 UTC by benanil

I've got little job to finish.

2023-04-18 15:38 UTC, afraidofdark requested changes

2023-04-18 15:38 UTC, afraidofdark commented on Editor/Workspace.cpp
> +                                                      XmlNodeSettings.data());
use Util.h
CreateXmlNode

2023-04-18 15:38 UTC, afraidofdark commented on Editor/Workspace.cpp
> +      size_t numCustomRes = pluginWindow->m_screenResolutions.size() -
there is a potential here that numCustomRes is near inf ( when the subtraction becomes negative )
Why don't you just use int ?

2023-04-18 15:38 UTC, afraidofdark commented on Editor/Workspace.cpp
> +      for (size_t i = 0; i < numCustomRes; ++i)
this code may run to infinity, size_t and uing is abit dangerous in that sense, either add proper checks or use int.

2023-04-18 15:38 UTC, afraidofdark commented on Editor/Workspace.cpp
> +    void Workspace::DeSerializeSimulationWindow(XmlDocumentPtr lclDoc)
const XmlDocumentPtr& settingsDoc better suits this function

2023-04-18 15:38 UTC, afraidofdark commented on Editor/Workspace.cpp
> +      XmlDocument* doc = lclDoc.get();
why not keep using lclDoc ? why need to get the raw pointer ?

2023-04-18 15:38 UTC, afraidofdark commented on Editor/Workspace.cpp
> +      const size_t defaultCnt = pluginWindow->m_numDefaultResNames;
m_numDefaultResNames is int, there is an implicit type cast here. Why you don't see the warnings ?
And why are you using size_t ? int is better suited.

2023-04-18 15:38 UTC, afraidofdark commented on Editor/Workspace.cpp
> +      const size_t defaultCnt = pluginWindow->m_numDefaultResNames;
if using int requires many typecast for size_t, you may use size_t otherwise it is safer and more advantageous

2023-04-18 15:38 UTC, afraidofdark commented on Editor/Workspace.h
> +      void SerializeSimulationWindow(XmlDocumentPtr lclDoc) const;
consider giving a better name to lclDoc such as const XmlDocumentPtr& settingsDoc

2023-04-18 18:45 UTC, benanil commented on Editor/Workspace.cpp
> +      for (size_t i = 0; i < numCustomRes; ++i)
there is no possibility that this code will run infinitely. we may not trust loading code but this is saving code.

2023-04-18 19:18 UTC, benanil commented on Editor/Workspace.cpp
> +      for (size_t i = 0; i < numCustomRes; ++i)
its certain that numCustomRes is going to be zero or greater than zero so there is no possibility that it runs infinity
it makes sense when we read from xml but we are writing to it.

2023-04-18 20:27 UTC, benanil commented on Editor/Workspace.cpp
> +      XmlDocument* doc = lclDoc.get();
because WriteAttr function accepts raw pointer. so this is cleaner than writing lclDoc.get() many times.

2023-04-18 20:29 UTC, benanil commented on Editor/Workspace.cpp
> +                                                      XmlNodeSettings.data());
alright.

2023-04-18 20:45 UTC, benanil commented on Editor/Workspace.cpp
> +      const size_t defaultCnt = pluginWindow->m_numDefaultResNames;
I've converted m_numDefaultResNames to int.

2023-04-19 11:01 UTC, afraidofdark approved these changes

2023-04-19 11:11 UTC, merged