Took 475 ton mapping reinhard aces
Oyun-Teknolojileri/ToolKit pull request #40
Opened 2022-12-13 12:08 UTC by fcturan20

[TOOK-475](https://oyunteknolojileri.atlassian.net/browse/TOOK-475?atlOrigin=eyJpIjoiMDIxYTQ0ZGNkZGZlNGU5OGJjZTYxMzI4YjVlNmQzYzAiLCJwIjoiaiJ9)

2022-12-13 12:18 UTC, afraidofdark requested changes

2022-12-13 12:18 UTC, afraidofdark commented on Editor/App.cpp
> +          myEditorRenderer->m_params.AcesTonemapper =
why aces tonemapper if it also contains reinhard implementation ?

ToneMapper looks more suitable ?

2022-12-13 12:18 UTC, afraidofdark commented on ToolKit/Pass.h
> +    bool AcesTonemapper        = true; //!-< If false, Tonemapper is Reinhard
use an enum TonePamTechniques { Reinhard, Aces }

2022-12-13 12:18 UTC, afraidofdark commented on ToolKit/Pass.h
> +    int acesTonemapper = 0; // !-< 0: Tonemap off, 1: Reinhard, 2: ACES
use enum

2022-12-13 12:18 UTC, afraidofdark commented on ToolKit/Renderer.cpp
> +        case ParameterVariant::VariantType::UInt:
is this valid in opengl es 3.0 shader model 3.0 ?

2022-12-13 19:46 UTC, fcturan20 commented on ToolKit/Renderer.cpp
> +        case ParameterVariant::VariantType::UInt:
1uiv is valid, so it should be. We're already using it for bool.

2022-12-13 19:51 UTC, fcturan20 commented on Editor/App.cpp
> +          myEditorRenderer->m_params.AcesTonemapper =
I agree that Aces is better but it's better to give user the choice. We don't have complicated tonemapper settings (max white point etc.) anyway, at least this should be available.

2022-12-14 09:53 UTC, afraidofdark approved these changes

2022-12-14 10:44 UTC, merged